### ISSUE TITLE
Les Mini-graph ne s'affichent pas sur le fond de la carte

### ISSUE THREAD

**Issue by Veher-el** [herveaurel/HomeAssistant#10]
Bonjour

Avant tout félicitation pour ce job très inpirant et le partage global

Un point me semble bizarre concernant la structure de ton code sur la partie des pièces qui affichent la température en fond.

En effet, il n'est ni déclaré le template "graph_temp" ni le custom_field avec le composant graph_temp.

Pour que la courbe s'affiche, j'ai du ajouter dans la partie template (voir ci dessous) la déclaration de graph_temp
et dans la partie custom_fields la référence au graph

```
- type: custom:button-card
                        entity: light.sejour
                        template:
                            - ...
                            - graph_temp
...
                       custom_fields:
                             ...
                             graph_temp:
                                card:
                                type: custom:mini-graph-card
                                entities:
                                  - sensor.blink_camera_entree_temperature

```
Or rien ne s'affiche pas exactement comme toi (le fond est plus marqué, moins transparent et moins haut)

![image](https://user-images.githubusercontent.com/88648983/215252690-c561d932-f0fe-40db-9cda-4c45132297ab.png)

(Sans doute ai je mal appréhender quelque chose dans la gestion des template car ton code l'aurais forcément intégré)
