### ISSUE TITLE
person_card_var_device ne fonctionne pas

### ISSUE THREAD

**Issue by rhcpdu13** [herveaurel/HomeAssistant#15]
Hello, je n'arrive pas à faire fonctionner le retour d'état de charge sur la carte person_card.
J'ai bien mon retour d'état de sensor.pixel_7_pro_battery_state qui fonctionne avec charging, discharging, mais l'affichage sur le dashboard ne m'affiche pas le cercle de charge.
Voici la partie du code : 
```
  person_card_var_device:
    styles:
      card:
        - border: |
            [[[
              if (variables.var_state  == "Charging")
                return " 1px dashed var(--color-icon-yellow) " 
              if (variables.var_state  == "Full")
                return " 1px dashed var(--color-red) "                
              if (variables.var_level  < 30)
                return " 1px solid var(--color-red) "                        
              return ""
            ]]]
  
  person_card_frank:
    entity: person.frankblemont
    template:
      - person_card
    label: |
      [[[return states["sensor.frank_gps_simple"].state]]]
    styles:
      label:
        - white-space: normal
    custom_fields:
      jauge-cercle:
        card:
          type: custom:hatc-gauge-card
          entity: sensor.pixel_7_pro_battery_level
          title:
            name: false
            icon: false
          gauge:
            icon: false
            font-size: 11px
            text-color: severity
            max_value: 100
            friendly_name: false
            unit_of_measurement: false
            severity:
              - color: var(--text-off)
              - color: var(--color-blue)
                from: 99
                to: 51
              - color: var(--color-yellow)
                from: 31
                to: 50
              - color: var(--color-red)
                from: 0
                to: 30
      bouton:
        card:
          type: horizontal-stack
          cards:
            - type: custom:button-card
              entity: device_tracker.pixel_7_pro
              template:
                - sub_button
                - sub_button_state
                - person_card_var_device
              variables:
                var_state: |
                  [[[ 
                    return states['sensor.pixel_7_pro_battery_state'].state 
                  ]]]
                var_level: |
                  [[[ 
                    return states['sensor.pixel_7_pro_battery_level'].state 
                  ]]]
              icon: mdi:cellphone
```

Aurais-tu une piste pour m'aider ? Merci !
