### ISSUE TITLE
batterie_faible

### ISSUE THREAD

**Issue by rhcpdu13** [herveaurel/HomeAssistant#16]
Hello, j'ai un problème d'affichage des batteries faibles :
```
            titre_batterie_faible:
              - filter: drop-shadow(0px 2px 2px rgba(0,0,0,0.3))
              - padding: |
                  [[[
                    if (states['sensor.batterie_faible'].state == '')
                      return "0px 0px 0px 0px" ;
                    return "10px 0px 01px 0px" ;
                  ]]]          
```
Il m'affiche 5 objets (zwave uniquement apparemment) avec une batterie faible :
![1](https://github.com/herveaurel/HomeAssistant/assets/15130377/767459d6-6483-4c57-a8a4-93c753a3c8fd)

j'ai tenté dans le code de commenter ces lignes pour voir le résultat en % : 
```
              states.sensor                  
              | selectattr('attributes.device_class', 'defined') 
              | selectattr('attributes.device_class', '==', 'battery') 
              | rejectattr('state', 'in', ['unavailable', 'unknown'])
              | rejectattr('state', 'eq', '100')   
              | selectattr('state', 'lt', '30')
              | map(attribute='name') | list | join(' , ')%}
              {%set etat_pile_faible =
```

Et on voit bien que le % est à 100%, j'ai quand même vérifié mes objets, et ils sont bien à 100%
![2](https://github.com/herveaurel/HomeAssistant/assets/15130377/6ab79395-796f-4c1a-a61b-b8e57a7e4b61)

Tu aurais une piste du problème ?
Merci !

**Comment by herveaurel** [comment]
Etonnant car cette ligne rejette les états à 100% 
`| rejectattr('state', 'eq', '100') `
Essaie peut-etre de mettre la valeur "100.0" à la place car apparement tes remontées sont sous ce format.

**Comment by rhcpdu13** [comment]
Merci pour ta réponse !
Bon ya du mieux mais maintenant il m'affiche ça : 
![3](https://github.com/herveaurel/HomeAssistant/assets/15130377/1fc2603c-968e-4472-887b-c39ed968d23d)

J'ai aussi essayé de forcer la précision des états à 100% au lieu de 100.0%, mais il ne les prend pas en compte.

**Comment by herveaurel** [comment]
C'est en effet très pénible. 
Je n'ai pas la solution à ce problème que je n'ai pas. 
Tout comme je n'ai jamais trouvé pour le moment la non prise en compte des valeurs sous les 10%.

**Comment by rhcpdu13** [comment]
Ok pas de soucis. En // j'utilise battery-state-card https://github.com/maxwroc/battery-state-card avec ce code-ci  : 
```
type: custom:battery-state-card
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
title: Batteries
sort_by_level: asc
tap_action: more-info
bulk_rename:
  - from: Battery Level
    to: sensor
  - from: /\s(temperature|temp)\s/
    to: ' temp. '
filter:
  include:
    - name: entity_id
      value: '*_battery'
    - name: entity_id
      value: '*_battery_level'
    - name: entity_id
      value: '*_batterie'
    - name: attributes.device_class
      value: battery
  exclude:
    - name: state
      value: 40
      operator: '>'
    - name: entity_id
      value: '*_low_battery_level'
    - name: entity_id
      value: '*_voltage_batterie'
    - name: state
      value: Unavailable
    - name: state
      value: Unknown
    - name: state
      value: 'Off'
    - name: state
      value: 'On'
```
Si ça peut t'inspirer pour une intégration :)
